name: spendhelper
description: "Spending Helper App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  currency_text_input_formatter: ^2.1.13
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.2.0
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  meta: ^1.10.0
  path_provider: ^2.1.2
  pedantic: ^1.11.1
  sqflite: ^2.3.2
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env